# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ProductBrowser' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Ensure NetworkExtension framework is linked for @react-native-community/netinfo
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |native_target|
        if native_target.name == 'ProductBrowser'
          native_target.build_configurations.each do |config|
            flags = config.build_settings['OTHER_LDFLAGS'] || ['$(inherited)']
            flags = [flags] if flags.is_a?(String)
            unless flags.any? { |f| f.include?('NetworkExtension') }
              flags.push('-framework', '"NetworkExtension"')
              config.build_settings['OTHER_LDFLAGS'] = flags
            end
          end
          aggregate_target.user_project.save
        end
      end
    end
  end
end
